BetTest/Models/Domain/Cart.cs
namespace BetTest.Models.Domain
{
    public class Cart
    {
        public Guid Id { get; set; }
        public string userId { get; set; }
        public DateTime Adddate { get; set; }
        public decimal? CartTotal { get; set; }
        
    }
}

BetTest/Controllers/CartsController.cs
using BetTest.Areas.Identity.Data;
using BetTest.Data;
using BetTest.Models.Domain;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace BetTest.Controllers
{
    [Authorize]
    public class CartsController : Controller
    {
        private readonly BetTestDBContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public CartsController(BetTestDBContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var cart = await _context.ViewCart.Where(c => c.UserId == userId).ToListAsync();    
            return View(cart);
        }
        [HttpPost]
        public async Task<IActionResult> SendEmail()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var userEmail = User.FindFirstValue(ClaimTypes.Email);
          var cartItems = await _context.ViewCart.Where(c => c.UserId == userId).ToListAsync();
            string bodytext = "";
            var emaildto = new EmailDto();
            emaildto.To = userEmail;
            emaildto.Subject = "Your Purchases";
            foreach (var e in cartItems)
            {
                
                string html = "<table border = '1'><tr><td>Product</td><td>Price</td><td>Total</td></tr><tr><td>{Product}</td><td>{Price}</td><td>{Total}</td></tr></table>";
                string product = e.Name;
                string price = e.Price.ToString();
                string total = e.TotalInclVat.ToString();
                html = html.Replace("{Product}", product).Replace("{Price}", price).Replace("{Total}", price);
                bodytext = html;
            }
           
            emaildto.Body = bodytext;
            return RedirectToAction("Index", "Products");
        }
        
    }
}

BetTest/Views/Carts/Index.cshtml
@model List<BetTest.Models.Domain.ViewCart>


<div class="row md-Padding-Top-25">
    <div class="col-md-2">
        <h1> Cart Items</h1>
    </div>
    <br />
    
</div>

<table class="table">
    <thead>
        <tr>
            <th>Order No.</th>
            <th>Photo</th>
            <th hidden="hidden">Id</th>
            <th>Name</th>
            <th>Description</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Cost price</th>
            <th>Vat</th>
            <th>Total</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var cartItem in Model)
        {

            <tr>
                <td>@cartItem.CartId</td>
                <td>
                    @{
                        var imageText = "";
                        if (cartItem.Photo.EndsWith("/NoImage.jpg"))
                        {
                            imageText = "No Image for" + cartItem.Name.Trim() + "-" + cartItem.Description.Trim();
                        }
                        else
                        {
                            imageText = "No Image for" + cartItem.Name.Trim() + "-" + cartItem.Description.Trim();
                        }
                    }
                    <img src="@cartItem.Photo" class="img-fluid" alt="@imageText" title="@imageText" />
                </td>
                <td hidden="hidden">@cartItem.Id</td>
                <td>@cartItem.Name</td>
                <td>@cartItem.Description</td>
                <td>@cartItem.Qunatity</td>
                <td>@cartItem.Price</td>
                <td>@cartItem.LineTotal.ToString("0.00")</td>
                <td>@cartItem.Vat.ToString("0.00")</td>
                <td>@cartItem.TotalInclVat.ToString("0.00")</td>

            </tr>

        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan"3">Total</td>
            <td>@Model.Sum(i => i.TotalInclVat).ToString("0.##")</td>
            <td>
           
            </td>
            <td>
                <form asp-action="SendEmail" asp-controller="Carts">
                    <button type="submit" class="btn btn-info btn-sm" ><i class="fa-solid fa-envelope fa-2x"></i></button>

                </form>
            </td>
        </tr>
    </tfoot>
</table>